### PR TITLE
Emoji 14 support

### PR DESCRIPTION
**Pull request by iamcal**
Unicode released the new standard in September.

There are not yet any images for Apple (first half of 2022), or Google (Android has been updated, but not the noto-emoji repo), or Twitter, or Facebook.

I wont merge this branch to master until at least Google and Apple have released images.

### CODE REVIEW

**Comment by stof** [comment]
The noto-emoji repository has been updated in https://github.com/googlefonts/noto-emoji/pull/369

**Comment by iamcal** [comment]
google images have been updated and sheets rebuilt. i will do all the optimization once we have more image sets

**Comment by stof** [comment]
@iamcal will you merge this and do a release supporting Emoji 14 with the google images, or will it wait months until Apple releases its images ?

**Comment by iamcal** [comment]
i'm planning to wait to _merge_ it, but i think it probably makes sense to optimize everything so that people can use the branch version for now

**Comment by stof** [comment]
@iamcal the new Apple emojis are now available according to emojipedia

**Pull request merged**
