### PR TITLE
update google images to nougat

### PR DESCRIPTION
**Pull request by iamcal**

### CODE REVIEW

**Comment by iamcal** [comment]
issues which block this from being merged:

* we're missing the flag-us and flag-no images. not sure where they've gone
* nougat does not have all the same family ligatures as marshmallow had. need to find where they're gone and re-map them
* after that, need to do a full optimization, data rebuild and sheet rebuild

**Comment by iamcal** [comment]
missing flags are:

* `flag-no` `1F1F3-1F1F4`
* `flag-us` `1F1FA-1F1F8`

**Comment by iamcal** [comment]
i've fixed the family ligature mappings in `extract.pl`, but it's giving me errors every other time i run it now. it seems like it's failing to clear state or something

**Comment by noodlebox** [comment]
I noticed the same issue when trying this myself. A random subset of the family sequences are missing each run, though there's always the same number of extracted images (before the additional moving/copying). The non-deteministic behavior is likely caused by Perl's random ordering of keys from a hash, and my guess is that not all of them are being iterated over somewhere (though I'm not sure where).

I'm not really familiar enough with Perl to fix it (just happened to choose Python long ago :P), but I thought it might be a better idea to just use the images straight from the source, [noto-emoji](https://github.com/googlei18n/noto-emoji), instead. I wrote some quick scripts to use those and the gaps in google's sprite sheet finally seem to be filled. I can clean this up a little and make a pull request if you'd like.

sheet_google_16

**Comment by iamcal** [comment]
i'm going to keep this branch around for a while to understand why the perl extractor was failing, but this has now been superseded by pulling the images from the noto repo

**Comment by stof** [comment]
@iamcal after 5 years, maybe this PR should be closed

**Comment by iamcal** [comment]
you know, i think you're right 😂

**Pull request closed without merging**
