### PR TITLE
Facebook/Messenger images

### PR DESCRIPTION
**Pull request by iamcal**

### CODE REVIEW

**Comment by iamcal** [comment]
this PR supersedes #74 and will fix #56

**Comment by iamcal** [comment]
We're getting there slowly, but still missing some obvious images:

https://unicodey.com/emoji-data/sheet_messenger_64.png

I spot at least 18 missing skin tone variations and 2 clocks. it falls back to apple emoji in non-skin-tone cases, so it can be hard to spot things which are missing (and likely exist on FB's side)

**Comment by Crissov** [comment]
Did you try to change the `User-Agent` that `wget` sends? I think I remember reading that Facebook throttles or blocks “non-browsers” sometimes.

**Comment by iamcal** [comment]
yup, that did. i've now merged _messenger_ images to master. not sure what to do about facebook emoji - i know they exist in higher resolution, but not sure where to get them yet

**Pull request merged**
