### PR TITLE
update to unicode 9 / emoji 4

### PR DESCRIPTION
**Pull request by iamcal**

### CODE REVIEW

**Comment by iamcal** [comment]
i now have the catalog building from the latest unicode data, along with working shortcodes.

next step is to merge emoji like `"woman-bouncing-ball:skin-2"` as a skin variation of `"woman-bouncing-ball"` (and make sure skin variations are correctly sorted).

after that, i can start updating images

**Comment by iamcal** [comment]
Remaining issues:
* Missing the category ordering information; i need to pull this from Mac OS
* Previously `U+1F373 COOKING` was defined as `:egg:`, but now we have `U+1F95A EGG`. The former is a fried egg. Considering changing the old one to `:fried_egg:`

After that I'll merge so that the data is current, before I start working on updating all the image sets.

**Comment by r14n** [comment]
anxiously awaiting!

**Comment by iamcal** [comment]
i'm mostly happy with the data now, though still missing some categories which should be easy to pull; copying them from their equivalent codepoints (e.g. the non-gendered version).

i've updated the images for google, twitter, emojione and fb/messenger. apple is the main one remaining

**Comment by iamcal** [comment]
all emoji now have category info. i've also added source unicode version (new `added_in` field). the bulk os the remaining work is apple images (updating the extraction tool to support ttc files)

**Comment by iamcal** [comment]
google images have been updated - latest master rev of the noto repo fixed flag images, so they're all working again.

**Pull request merged**
