### PR TITLE
Emoji V11.0 and Apple Emoji Update

### PR DESCRIPTION
**Pull request by leplay**
macOS 10.14 (Mojave)

### CODE REVIEW

**Comment by iamcal** [comment]
this looks great, thank you. i'ts going to be a little while before i can review and merge, but hopefully this evening (PST)

**Comment by leplay** [comment]
I'm glad to help. I found the emoji list url ( http://www.unicode.org/~scherer/emoji4unicode/snapshot/full.html ) is 403 now, so I couldn't build new catalog. Is there any web page can replace it?

**Comment by iamcal** [comment]
the final version of that file is already in the repo (`build/full.html`) so that's ok.

there are a bunch of other steps involved in building the updated map, including supplying new short names and dealing with changes in the format of various data files. i'm working on those changes in a branch currently

**Comment by leplay** [comment]
That's great. Thanks for your work.

**Comment by skewart** [comment]
@iamcal thank you for your work on this!  Really looking forward to when that branch can get merged!

**Comment by BenjaminHoegh** [comment]
This is some amazing work 👍 

@leplay I can recommend you use https://emojipedia.org

**Comment by tsuyoshizawa** [comment]
Is there any update?

**Comment by skittles9823** [comment]
Hope this gets added soon-ish 🤔

**Comment by rijn** [comment]
Shortnames for items added in Emoji 11
```
1F970;smiling_face_with_3_hearts
1F975;hot_face
1F976;cold_face
1F973;partying_face
1F974;woozy_face
1F97A;pleading_face
{MAN/WOMAN}{SKIN}-200D-1F9B0;{GENDER}_red_haired
{MAN/WOMAN}{SKIN}-200D-1F9B1;{GENDER}_curly_haired
{MAN/WOMAN}{SKIN}-200D-1F9B2;{GENDER}_bald
{MAN/WOMAN}{SKIN}-200D-1F9B3;{GENDER}_white_haired
1F9B8{SKIN}-200D-{MAN/WOMAN};{GENDER}_superhero
1F9B9{SKIN}-200D-{MAN/WOMAN};{GENDER}_supervillain
1F9B5{SKIN};leg
1F9B6{SKIN};foot
1F9B4;bone
1F9B7;tooth
1F97D;goggles
1F97C;lab_coat
1F97E;hiking_boot
1F97F;woman’s_flat_shoe
1F99D;raccoon
1F999;llama
1F99B;hippopotamus
1F998;kangaroo
1F9A1;badger
1F9A2;swan
1F99A;peacock
1F99C;parrot
1F99E;lobster
1F99F;mosquito
1F9A0;microbe
1F96D;mango
1F96C;leafy_green
1F96F;bagel
1F9C2;salt
1F96E;moon_cake
1F9C1;cupcake
1F9ED;compass
1F9F1;bricks
1F6F9;skateboard
1F9F3;luggage
1F9E8;firecracker
1F9E7;red_envelope
1F94E;softball
1F94F;flying_disc
1F94D;lacrosse
1F9FF;nazar_amulet
1F9E9;jigsaw
1F9F8;teddy_bear
265F-FE0F;chess_pawn
1F9EE;abacus
1F9FE;receipt
1F9F0;toolbox
1F9F2;magnet
1F9EA;test_tube
1F9EB;petri_dish
1F9EC;dna
1F9EF;fire_extinguisher
1F9F4;lotion_bottle
1F9F5;thread
1F9F6;yarn
1F9F7;safety_pin
1F9F9;broom
1F9FA;basket
1F9FB;roll_of_paper
1F9FC;soap
1F9FD;sponge
267E-FE0F;infinity
1F3F4-200D-2620-FE0F;pirate_flag
```

**Comment by slavaslava56ru** [comment]
@iamcal Hi, merge these branches please

**Comment by leplay** [comment]
I create a new repository on top of this, check out [https://github.com/leplay/emoji-sheet](https://github.com/leplay/emoji-sheet)

**Comment by slavaslava56ru** [comment]
Hi! Thank you very much, can you update the config to a new one?
https://github.com/leplay/emoji-sheet/blob/master/emoji.json

вс, 7 апр. 2019 г. в 22:24, leplay <notifications@github.com>:

**Comment by leplay** [comment]
The data in it is parsed from Unicode 12.0 (https://unicode.org/Public/emoji/12.0/emoji-test.txt)，but some fields are different from this project.

You can check https://github.com/leplay/emoji-sheet/blob/master/sheet/result.json , it contains provider support and emoji position info.

**Comment by rugk** [comment]
Any news here? This would fix https://github.com/iamcal/emoji-data/issues/145

**Comment by xaviershay** [comment]
I have time to spend on this next week, would appreciate any pointers to "what work is still needed", I'm pretty new to the library but am motivated to get this done! 🙏

**Comment by xaviershay** [comment]
So I spent some time on this. Things I learned:

* I don't think this PR is complete. `emoji.json` hasn't been updated, which is file that is used by anyone importing this lib. (also mentioned by author in [earlier comment](https://github.com/iamcal/emoji-data/pull/146#issuecomment-435263403)
* `build/build_map.php` is what would update `emoji.json`, but running it results in a huge number of "no data" output (which don't occur on master) and doesn't update it with any new emoji.
* `build/README.md` contains instructions for downloading/using http://www.unicode.org/~scherer/emoji4unicode/snapshot/full.html which hasn't been available since [March last year](https://web.archive.org/web/20180501000000*/http://www.unicode.org/~scherer/emoji4unicode/snapshot/full.html). Earlier author comment implies it shouldn't be needed ("`full.html` already checked in), but I'm skeptical based on errors I'm seeing. I'm not sure what this file is used for yet, but there is a somewhat arbitrary looking `build/source_html.patch` that is applied to it. I'm guessing this is for getting the various vendor images? [This page](https://unicode.org/emoji/charts/full-emoji-list.html) is probably a replacement, though likely isn't an exact drop in.

**Comment by xaviershay** [comment]
@rijn did you just make those short names up, or did you source that from somewhere?

**Comment by xaviershay** [comment]
https://github.com/iamcal/emoji-data/pull/152 builds on this and, while not quite ready for merge, should be usable for anyone desperate to get (most) of the new emoji.

**Comment by rijn** [comment]
@xaviershay I made it manually from the [list](https://unicode.org/Public/emoji/12.0/emoji-test.txt).

**Comment by iamcal** [comment]
#152 got merged to support emoji/unicode 11

**Comment by slavaslava56ru** [comment]
Hey, can you please add the sprite to the repository

сб, 18 мая 2019 г. в 01:23, Cal Henderson <notifications@github.com>:

**Comment by slavaslava56ru** [comment]
with new emoji :)

чт, 23 мая 2019 г. в 09:29, Слава Характеров <slavaslava56ru@gmail.com>:

**Comment by iamcal** [comment]
sprite sheets have been updated in the repo

**Pull request closed without merging**
