### PR TITLE
Include Google and Twitter SVGs

### PR DESCRIPTION
**Pull request by ccorcos**
As I commented in https://github.com/iamcal/emoji-data/issues/174 I'd like some larger emoji images (I'm rendering some 78px emojis in some places and with a retina display, that requires 156px). 

I noticed that once we get up to pngs that large, the SVGs are actually smaller. I notices that Google and Twitter provide SVG so I modified two scripts to collect them into this repository: `build/google/makeSvg.sh` and `build/twitter/grab.php`.

**Note: First time ever using PHP**

I don't know much about TTC fonts, but ideally we could extract Apple SVGs as well. Any ideas how to do that?

Also, it might make sense to integrate these in the build pipeline for `emoji-datasource-google` and `emoji-datasource-twitter`.

Thanks!

### CODE REVIEW

**Comment by mikecann** [comment]
Also very keen on getting SVG's any reason this isnt merged?

**Comment by ccorcos** [comment]
No one has ever responded...

**Comment by mikecann** [comment]
@iamcal Any reason why this cant be merged?

**Comment by iamcal** [comment]
Sorry for not responding sooner - The Apple emoji font uses bitmaps, not vectors/SVG, so there's no way to get SVGs for either Apple or Facebook images. As a result, I don't think it makes sense for this library to include SVG images. The purpose of this library is to make it easy to use bitmap'd emoji from the various icon sets, either as sheets or as individual images. If you want to use the SVGs from either Twemoji or Noto, then you can just use them directly from those projects.

**Pull request closed without merging**
