### PR TITLE
Speed up build_image.php

### PR DESCRIPTION
**Pull request by noodlebox**
For building a sprite sheet, a single call to `montage` is far faster than repeated calls to `composite`. This gives the same result with a ~50x speedup on my machine.

### CODE REVIEW

**Comment by iamcal** [comment]
This is a great approach. I meant to do this back when I started, but since you can't pass them on the commandline and have to use `popen()` i got lazy.

However, the ordering of output here is not the same as the original, so I can't merge it yet:
order

**Comment by iamcal** [comment]
(build time per sheet is now ~30s on my build box, instead of multiple minutes)

**Comment by noodlebox** [comment]
That's very strange, I get the correct order on mine. What version of imagemagick are you using? Mine is `ImageMagick 6.8.9-9 Q16 x86_64 2016-06-01`.

**Comment by iamcal** [comment]
It's older:

    # montage -version
    Version: ImageMagick 6.5.4-7 2014-02-10 Q16 OpenMP http://www.imagemagick.org
    Copyright: Copyright (C) 1999-2009 ImageMagick Studio LLC

After a yum upgrade I got:

    # montage -version
    Version: ImageMagick 6.7.2-7 2016-06-16 Q16 http://www.imagemagick.org
    Copyright: Copyright (C) 1999-2011 ImageMagick Studio LLC
    Features: OpenMP

That built the sheets correctly. I'll add a note to make sure the ImageMagick version is recent 👍

**Comment by iamcal** [comment]
note added in 1c5928f

**Pull request merged**
