### PR TITLE
Emoji 15.0 support

### PR DESCRIPTION
**Pull request by iamcal**
Tasks:

- [x] Update core data files and names
- [x] Update Apple images (from mac OS)
- [x] Update Google images (from Noto)
- [ ] Update Twitter images - work happening in this PR: https://github.com/jdecked/twemoji/issues/8
- [ ] Update Facebook images - Rollout started, but not yet visible to me
- [x] Optimize and publish

There are 31 added emoji in 15.0, and the table below tracks the progress of missing images across the four supported image sets as we drive towards the 15.0 release.

| Image Set | 14.0 Missing Images | 15.0 Missing Images |
|-----------|---------------------|---------------------|
| Apple     | 3                   | 3                   |
| Google    | 0                   | 0                   |
| Twitter   | 0                   | 31                  |
| Facebook  | 380                 | 55                  |

### CODE REVIEW

**Comment by Vlabala** [comment]
Hi, is there any prediction on what date you might finish this PR? :pray:

**Comment by iamcal** [comment]
I'll most likely merge it once Apple images are available, even if Twitter and Facebook images are not yet there.

**Comment by jakex7** [comment]
Hi @iamcal, I'd just like to mention that according to [Apple's release notes](https://support.apple.com/en-us/HT213268), version 15.0 comes with macOS 13.3.1 which has been released a while ago

**Comment by iamcal** [comment]
v15 support has been merged. I'll hold off on updating the NPM packages for a few days while I wait for bug reports from people who are using actively using the master branch

**Comment by jwheare** [comment]
I'll try to give this a test early next week.

**Comment by jwheare** [comment]
Looks good to me, deploying an update to IRCCloud with the latest data now.

**Comment by susnux** [comment]
Google images are not optimized and as such the "indexed" sheets (published on NPM) do not contain Emoji 15.

**Comment by iamcal** [comment]
Good catch - the quantized sheets for google did not get updated. I'll do a new build 👍

**Comment by iamcal** [comment]
Patch in #228

**Comment by iamcal** [comment]
Landed in v15.0.1

**Pull request merged**
